name: Rust Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with: # input params for this action
          toolchain: stable
          components: rustfmt
          override: true

      - name: Check formatting
        run: cargo fmt -- --check
